-- MySQL Script generated by MySQL Workbench
-- Mon May  1 15:35:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`Cliente` (
  `idCliente` VARCHAR(40) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`inventario` (
  `ProductoID` INT(1) NOT NULL auto_increment,
  `Nombre` VARCHAR(45) NOT NULL,
  `Precio` int NULL,
  `Cantidad` INT(10)  NOT NULL,
  `Venta` boolean NOT NULL, 
 
  PRIMARY KEY (`ProductoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`Empleados` (
  `idEmpleado` INT(1) NOT NULL auto_increment,
  `Nombre` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`agenda` (
  `contacto` INT(1) NOT NULL auto_increment,
  `Nombre` VARCHAR(45) NOT NULL,
  `Profesion` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45)  NOT NULL,
  PRIMARY KEY (`contacto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`Reservaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`Reservaciones` (
  `idReservaciones` INT(1) NOT NULL auto_increment,
  `Check_in` DATE NULL,
  `check_out` DATE NULL,
  `Tiempo_de_estancia` TIME NULL,
  `precio` INT NULL,
  `codigo_auth` varchar(10) NOT NULL,
  `Cliente_idCliente` varchar(40) NOT NULL,
  PRIMARY KEY (`idReservaciones`, `Cliente_idCliente`),
  INDEX `fk_Reservaciones_Cliente1_idx` (`Cli ente` ASC) VISIBLE,
  CONSTRAINT `fk_Reservaciones_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `test`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`ventas` (
  `idventas` INT(1) NOT NULL auto_increment,
  `fecha` DATETIME NOT NULL,
  `tipo_articulo` VARCHAR(45) NOT NULL,
  `nombre_articulo` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `cantidad` int not null,
  PRIMARY KEY (`idventas`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;